{
	"version": 1487951461,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/player-sheet0.png",
		"images/tiledbackground.png",
		"images/bullet-sheet0.png",
		"images/enemy-sheet0.png",
		"images/explosion-sheet0.png",
		"images/explosion-sheet1.png",
		"images/radar-sheet0.png",
		"images/radar-sheet1.png",
		"images/radar-sheet2.png",
		"images/blip-sheet0.png",
		"images/radarframe-sheet0.png",
		"images/tiledbackground2.png",
		"media/depthchargeshort.m4a",
		"media/depthchargeshort.ogg",
		"media/laserblast.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}